PMS/PMS/Models/team.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Models
{
    using System;
    using System.Collections.Generic;

    public partial class team
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public team()
        {
            this.CreateProjects = new HashSet<CreateProject>();
        }

        public int id { get; set; }
        public string lderUname { get; set; }
        public string memUname { get; set; }
        public string leader_name { get; set; }
        public string member_name { get; set; }
        public string usrname { get; set; }
        public Nullable<int> projectNo { get; set; }
        public string project_name { get; set; }
        public string state { get; set; }
        public IEnumerable<project> projects { get; set; }
        public IEnumerable<user> mt { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CreateProject> CreateProjects { get; set; }
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
        public virtual user user2 { get; set; }
    }
}

PMS/PMS/Controllers/TeamController.cs
using PMS.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace PMS.Controllers
{
    public class TeamController : Controller
    {
        pmsEcommerceEntities1 db = pmsEcommerceEntities1.getInstance();
        // GET: team
        [Authorize(Roles = "MD,MTL")]
        public ActionResult add_team()
        {
            var pros = getProjects().Where(x => x.stat == "to do");
            
            var mts = getDm().Where(x => x.Role == "MT");
            team PA = new team
            {
                
                mt = mts,
                projects = pros

            };
            return View(PA);
        }
        public IEnumerable<user> getDm()
        {
            var usr = db.users.ToList();
            return usr;
        }
        [Authorize(Roles = "MD")]
        public ActionResult ListTeam()
        {
            var t = getTeams();
            return View(t);
        }
        public IEnumerable<team> getTeams()
        {
            var t = db.teams.ToList();
            return t;
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "MD,MTL")]
        public ActionResult add_team(team o)
        {
            db.teams.Add(o);
            db.SaveChanges();

            // this noti for test
            tbl_Notification no = new tbl_Notification
            {
                ExtraColumn = "admin",
                Status = "/Notification/Test",
                Message = "MD " + User.Identity.Name + " have been add new Team"
            };
            db.tbl_Notification.Add(no);
            db.SaveChanges();

            return RedirectToAction("ListTeam");
        }
        [HttpGet]
        [Authorize(Roles = "MD,MTL")]
        public ActionResult Details(int id)
        {
            var t = getTeams().SingleOrDefault(y => y.id == id);
            return View(t);
        }
        public ActionResult Deleteteam()
        {
            return View();
        }
        [HttpGet]
        [Authorize(Roles = "MTL,MD")]
        public ActionResult Deleteteam(int id)
        {
            var t = getTeams().SingleOrDefault(y => y.id == id);
            return View(t);
        }
        [HttpPost]
        [Authorize(Roles = "MD,MTL")]
        public ActionResult Deleteteam(team o)
        {
            var t = getTeams().SingleOrDefault(y => y.id == o.id);
            db.teams.Remove(t);
            db.SaveChanges();
            return RedirectToAction("ListTeam");
        }
        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            team t = db.teams.Find(id);
            if (t == null)
            {
                return HttpNotFound();
            }
            return View(t);
        }

        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "MD,MTL")]
        public ActionResult EditTeam(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var Update = db.teams.Find(id);
            if (TryUpdateModel(Update, "",
               new string[] { "leader_name","member_name" }))
            {
                try
                {
                    db.SaveChanges();

                    return RedirectToAction("ListTeam");
                }
                catch (RetryLimitExceededException /* dex */)
                {
                    //Log the error (uncomment dex variable name and add a line here to write a log.
                    ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists, see your system administrator.");
                }
            }
            return View(Update);
        }
        public IEnumerable<project> getProjects()
        {
            var pros = db.projects.ToList();
            return pros;
        }


    }
}

PMS/PMS/Views/Team/Deleteteam.cshtml
@model PMS.Models.team

@{
    ViewBag.Title = "Deleteteam";
    Layout = "~/Views/Shared/_admin_MD_TL.cshtml";
}

<h2>Deleteteam</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>team</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.project_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.project_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.member_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.member_name)
        </dd>

        
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "ListTeam")
        </div>
    }
</div>

PMS/PMS/Views/Team/Details.cshtml
@model PMS.Models.team

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_admin_MD_TL.cshtml";
}

<h2>Details</h2>

<div>
    <h4>team</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.leader_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.leader_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.member_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.member_name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("information", "Details", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "ListTeam")
</p>

PMS/PMS/Views/Team/Edit.cshtml
@model PMS.Models.team

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_admin_MD_TL.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>team</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        
        <div class="form-group">
            @Html.LabelFor(model => model.leader_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.leader_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.leader_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.member_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.member_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.member_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "ListTeam")
</div>

PMS/PMS/Views/Team/ListTeam.cshtml
@model IEnumerable<PMS.Models.team>

@{
    ViewBag.Title = "ListTeam";
    Layout = "~/Views/Shared/_admin_MD_TL.cshtml";
}

<h2>ListTeam</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table table-bordered table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.project_name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.member_name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.project_name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.member_name)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
            @Html.ActionLink("Details", "Details", new { id=item.id }) |
            @Html.ActionLink("Delete", "Deleteteam", new { id=item.id })
        </td>
    </tr>
}

</table>

PMS/PMS/Views/Team/add_team.cshtml
@model PMS.Models.team

@{
    ViewBag.Title = "add_team";
    Layout = "~/Views/Shared/_admin_MD_TL.cshtml";
}

<h2>add_team</h2>


@using (Html.BeginForm("add_team", "Team", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>team</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        
        <div class="form-group">
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.member_name, new SelectList(Model.mt, "Username", "Username")," Select MT member", new { @id = "mt", @class = "form-control", @style = "width:350px;height:33px;display:inline-block;font-size:12px" , @required = true })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.project_name, new SelectList(Model.projects, "name", "name")," Select From projects",new { @id = "pro", @class = "form-control", @style = "width:350px;height:33px;display:inline-block;font-size:12px" , @required = true})
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
            
    </div>
    
}

<div>
    @Html.ActionLink("Back to List", "ListTeam")
</div>

<script>
    $(document).ready(function () {
        $("#mt option:first-child").attr("disabled", "true");
    });

</script>

<script>
    var coll = document.getElementsByClassName("collapsible");
    var i;

    for (i = 0; i < coll.length; i++) {
        coll[i].addEventListener("click", function () {

            this.classList.toggle("active");
            var content = this.nextElementSibling;
            if (content.style.display === "block") {
                content.style.display = "none";
            } else {
                content.style.display = "block";
            }
        });
    }
</script>