PMS/PMS/Models/project.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public project()
        {
            this.projectAssigns = new HashSet<projectAssign>();
        }
    
        public int id { get; set; }
        public string cust_name { get; set; }
        public string name { get; set; }
        public string descrption { get; set; }
        public string usrname { get; set; }
        public string stat { get; set; }
    
        public virtual user user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<projectAssign> projectAssigns { get; set; }
    }
}

PMS/PMS/Controllers/ProjectController.cs
using PMS.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace PMS.Controllers
{
    public class ProjectController : Controller
    {
        pmsEcommerceEntities1 db = pmsEcommerceEntities1.getInstance();
        // GET: Project

        [Authorize(Roles ="customer")]
        public ActionResult ListProjects()
        {
            var pros = getProjects().Where(x => x.usrname.Equals(User.Identity.Name) && x.stat == "to do");
            var md = getDm().Where(x => x.Role == "MD");
            var Asgn = db.projectAssigns.ToList();
            ProjectAssignment PA = new ProjectAssignment
            {
                mds = md,
                projects = pros,
                projectAsinss = Asgn

            };
            return View(PA);
        }
        public IEnumerable<project> getProjects()
        {
            var pros = db.projects.ToList();
            return pros;
        }

        [HttpGet]
        [Authorize(Roles = "customer")]
        public ActionResult AddProject()
        {
            return View();
        }
        [HttpPost]
        [Authorize(Roles = "customer")]
        public ActionResult AddProject(project pro)
        {
            pro.stat = "to do";
            db.projects.Add(pro);
            db.SaveChanges();
            // this noti for test
            tbl_Notification no = new tbl_Notification
            {
                ExtraColumn = "admin",
                Status = "/Notification/Test",
                Message = "Customer " + User.Identity.Name + " have been add post"
            };
            db.tbl_Notification.Add(no);
            db.SaveChanges();
            return RedirectToAction("ListProjects");
        }
        [HttpGet]
        [Authorize(Roles = "customer")]
        public ActionResult DetailsProCust(int id)
        {
            var pro = getProjects().SingleOrDefault(y => y.id == id);
            var mds = db.projectAssigns.ToList().Where(x => x.proId == id);
            ProjectAssignment PA = new ProjectAssignment {
                project = pro,
                projectAsinss = mds
                
            };
            return View(PA);
        }

        [HttpGet]
        [Authorize(Roles = "customer")]
        public ActionResult DeleteProjectCust(int id)
        {
            var pro = getProjects().SingleOrDefault(y => y.id == id);
            var mds = db.projectAssigns.ToList().Where(x => x.proId == id);
            ProjectAssignment PA = new ProjectAssignment {
                project = pro,
                projectAsinss =mds
            };
            return View(PA);
        }
        [HttpPost]
        [Authorize(Roles = "customer")]
        public ActionResult DeleteProjectCust(project pro)
        {
            var pros = getProjects().SingleOrDefault(y => y.id == pro.id);
            db.projects.Remove(pros);
            db.SaveChanges();
            return RedirectToAction("ListProjects");
        }
        [HttpGet]
        [Authorize(Roles = "customer")]
        public ActionResult EditProjectCust(int id)
        {
            var pr = db.projects.Find(id);
            var mds = db.projectAssigns.ToList().Where(x => x.proId == id);
            ProjectAssignment PA = new ProjectAssignment
            {
                project = pr,
                projectAsinss = mds
            };
            return View(PA);
        }
        [HttpPost]
        [Authorize(Roles = "customer")]
        public ActionResult EditProjectCust(project pro)
        {
            var p = db.projects.SingleOrDefault(x => x.id == pro.id);
            p.name = pro.name;
            p.descrption = pro.descrption;
            db.SaveChanges();
            return RedirectToAction("ListProjects");
        }
        /*********************************************/
        /*************Manage_project_to_create*************/
        [Authorize(Roles = "MD")]
        public ActionResult manage_project()
        {
            var pros = getProjects().Where(x => x.stat == "to do");
            var mtls = getDm().Where(x=>x.Role == "MTL");
            var mts = getDm().Where(x=>x.Role == "MT");
            CreateProject PA = new CreateProject {
                mtl = mtls,
                mt = mts ,
                projectss = pros
            
            };
            return View(PA);
        }
        [HttpPost]
        [Authorize(Roles = "MD")]
        public ActionResult manage_project(CreateProject c)
        {
            if (ModelState.IsValid)
            {
                db.CreateProjects.Add(c);
                db.SaveChanges();
                
            }
            return RedirectToAction("ListManageProject");
        }
        [Authorize(Roles = "MD")]
        public ActionResult ListManageProject()
        {
            var M = getManageProjects();
            return View(M);
        }
        public IEnumerable<CreateProject> getManageProjects()
        {
            var M = db.CreateProjects.ToList();
            return M;
        }
        [HttpGet]
        [Authorize(Roles = "MD")]
        public ActionResult Details_project(int id)
        {
            var M = getManageProjects().SingleOrDefault(y => y.id == id);
            return View(M);
        }

        [HttpGet]
        [Authorize(Roles = "MD")]
        public ActionResult DeleteManageProject(int id)
        {
            var M = db.CreateProjects.SingleOrDefault(y => y.id == id);
            return View(M);
        }
        [HttpPost]
        [Authorize(Roles = "MD")]
        public ActionResult DeleteManageProject(CreateProject pro)
        {
            var M = db.CreateProjects.SingleOrDefault(y => y.id == pro.id);
            db.CreateProjects.Remove(M);
            db.SaveChanges();
            return RedirectToAction("ListManageProject");
        }
        [HttpGet]
        [Authorize(Roles = "MD")]
        [Authorize(Roles = "MD")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CreateProject pro = db.CreateProjects.Find(id);
            if (pro == null)
            {
                return HttpNotFound();
            }
            return View(pro);
        }

        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public ActionResult EditPost(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var Update = db.CreateProjects.Find(id);
            if (TryUpdateModel(Update, "",
               new string[] { "pro_name", "strt_date", "end_date","stat","price","leader_name" }))
            {
                try
                {
                    db.SaveChanges();

                    return RedirectToAction("ListManageProject");
                }
                catch (RetryLimitExceededException /* dex */)
                {
                    //Log the error (uncomment dex variable name and add a line here to write a log.
                    ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists, see your system administrator.");
                }
            }
            return View(Update);
        }

        /*================================== YOUNIS WORK ================================ */
        public ActionResult List_dm()
        {
            var md = getDm().Where(x => x.Role == "MD");
            var pros = db.projects.ToList();
            var Asgn = db.projectAssigns.ToList();
            ProjectAssignment PA = new ProjectAssignment {
                mds = md,
                projects =pros,
                projectAsinss =Asgn

            };
            return View(PA);
        }
        public IEnumerable<user> getDm()
        {
            var usr = db.users.ToList();
            return usr;
        }
        [HttpGet]
        public PartialViewResult Mdir(int id)
        {
            var mds =  db.projectAssigns.ToList().Where(x=>x.proId==id);

            return PartialView("Mdir",mds);
        }
        [HttpPost]
        [Authorize(Roles = "customer")]
        public ActionResult AssignMD(projectAssign pa)
        {
            if (pa.name_dm == null || pa.name_dm.Equals("Assign MD"))
            {
                return Content("<script language='javascript' type='text/javascript'>alert('MD has not determined !!');window.location.replace('ListProjects');</script>");
            }
            else
            {
                db.projectAssigns.Add(pa);
                db.SaveChanges();
                // this noti for test
                tbl_Notification no = new tbl_Notification
                {
                    ExtraColumn = "MD",
                    Status = "/Notification/Test",
                    Message = "Customer " + User.Identity.Name + " Assign you to project"
                };
                db.tbl_Notification.Add(no);
                db.SaveChanges();

                return RedirectToAction("ListProjects");
            }
        }

        [HttpPost]
        [Authorize(Roles = "customer")]
        public ActionResult DeleteMDAssign(projectAssign PA)
        {
            var md = db.projectAssigns.SingleOrDefault(x => x.id == PA.id);
            db.projectAssigns.Remove(md);
            db.SaveChanges();
            return RedirectToAction("ListProjects");
        }


        /*-----------------------------------(Nourhan)----------------------------------*/
        /**********************************List project for MTL**********************************/
        public ActionResult layout()  /*******************just for show layout*************/
        {
            return View();
        }

PMS/PMS/Views/Project/AddProject.cshtml
@using (Html.BeginForm("AddProject","Project",FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <input type="text" name="cust_name" value="@HttpContext.Current.User.Identity.Name" hidden />
    <div class="form-group">
        <label class="control-label col-md-2">Project_Name</label>
        <div class="col-md-10">
            <input class = "form-control" type="text" name="name"  required/>
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">Description</label>
        <div class="col-md-10">
           <input class="form-control" type="text" name="descrption" required/>

        </div>
    </div>

    <input type="text" name="usrname" value="@HttpContext.Current.User.Identity.Name" hidden />

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" onclick="return alert('successful added')"/>
        </div>
    </div>
</div>
}

PMS/PMS/Views/Project/Details_project.cshtml
@model PMS.Models.CreateProject

@{
    ViewBag.Title = "Details_project";
    Layout = "~/Views/Shared/_Customer_Trainee.cshtml";
}

<h2>Details_project</h2>

<div>
    <h4>CreateProject</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.pro_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.pro_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.strt_date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.strt_date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.end_date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.end_date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.stat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.stat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.leader_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.leader_name)
        </dd>

        
        <dt>
            @Html.DisplayNameFor(model => model.user.Role)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.user.Role)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "EditPost", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "ListManageProject")
</p>

PMS/PMS/Views/Project/Edit.cshtml
@model PMS.Models.CreateProject

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Customer_Trainee.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CreateProject</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.pro_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.pro_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.pro_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.strt_date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.strt_date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.strt_date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.end_date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.end_date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.end_date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.stat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.stat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.stat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.leader_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.leader_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.leader_name, "", new { @class = "text-danger" })
            </div>
        </div>

        
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "ListManageProject")
</div>

PMS/PMS/Views/Project/Leave.cshtml
@model PMS.Models.CreateProject

@{
    ViewBag.Title = "Leave";
    Layout = "~/Views/Shared/_admin_MD_TL.cshtml";
}


<h3>Are you sure you want to leave " @Html.DisplayFor(model => model.pro_name) " project?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.strt_date)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.strt_date)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.end_date)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.end_date)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.price)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.price)
            </dd>

        </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="form-actions no-color">
            <input type="submit" value="Leave" class="btn btn-danger btn-lg" />
        </div>
        <br />
        <br />
        @Html.ActionLink("Back to List", "ListCurrentPMTL")
    }
</div>

PMS/PMS/Views/Project/ListCurrentPMT.cshtml
@model PMS.Models.CurrentPMTL
@{
    ViewBag.Title = "ListCurrentPMT";
    Layout = "~/Views/Shared/_Customer_Trainee.cshtml";
}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>


@if (!Model.tms.Any())
{
    <div style="padding-top:15%;">
        <center>
            <h>Sorry, no data to show ..</h><br />
            <img src="~/Image/shy.gif" style="width:200px;height:200px;" />
        </center>
    </div>

}



else
{
    <h2>Hi @User.Identity.Name! .. Those projects are in process:</h2>

    <table class="table">
        <tr>
            <th>
                @*@Html.DisplayNameFor(model => model.tms.project_name)*@
            </th>
        </tr>

        @foreach (var pro in Model.CurPros)
        {
            foreach (var item in Model.tms)
            {

                if (item.project_name == pro.pro_name && pro.state.Equals("doing") && item.member_name == User.Identity.Name)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.project_name)
                            <input type="text" id="proId" name="id" value="@item.id" hidden />
                        </td>
                        <td>
                            @*@Html.ActionLink("Leave", "Leave", new { id = item.id }, new { @class = "btn btn-danger" })*@
                            <button type="button" class="btn btn-danger" id="leaveBtn" onclick="leave()">Leave</button>

                        </td>
                    </tr>
                }
            }
        }

    </table>
    <button type="button" class="btn btn-primary" id="myBtn" data-toggle="modal" data-target="#myModal">Details</button>


}



<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog modal-lg">

        @*Modal content*@
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Details</h4>
                <div class="modal-body">

                    <table class="table">
                        <tr>
                            <th>
                                @*@Html.DisplayNameFor(model => model.tms.project_name)*@
                            </th>

                        </tr>

                        @foreach (var pro in Model.CurPros)
                        {
                            foreach (var tem in Model.tms)
                            {

                                if (tem.project_name == pro.pro_name && pro.state.Equals("doing") && tem.member_name == User.Identity.Name)
                                {
                                    <tr>
                                        <td>
                                            @tem.project_name
                                        </td>
                                        <td>
                                            @pro.leader_name
                                        </td>
                                        <td>
                                            @pro.price
                                        </td>
                                        <td>
                                            @pro.strt_date
                                        </td>
                                        <td>
                                            @pro.end_date
                                        </td>
                                    </tr>
                                }
                            }
                        }
                    </table>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    function leave() {
        var result = confirm("Are you sure you want to leave this project?")
        if (result == true) {
            $("#leaveBtn").attr("disabled", "true");
            $("#leaveBtn").html("Waiting...");
        }
    }
</script>

PMS/PMS/Views/Project/ListProjects.cshtml
@model PMS.Models.ProjectAssignment

@{
    ViewBag.Title = "Customer Home";
    Layout = "~/Views/Shared/_Customer_Trainee.cshtml";
}


<h2 id="add">Add Project</h2>
@Html.Partial("AddProject")
<br />
<hr />

<h2>Projects</h2>
<p>
    <a href="#add">Create New</a>
</p>
<table class="table" id="Plist">
    <tr>

        <th>
            @Html.DisplayNameFor(model => model.project.name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.project.descrption)
        </th>

        <th></th>
    </tr>

    @foreach (var item in Model.projects)
    {
        <tr>

            <td>
                @Html.DisplayFor(modelItem => item.name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.descrption)
            </td>

            <td>
                @Html.ActionLink("Edit", "EditProjectCust", new { id = item.id }) |
                @Html.ActionLink("Details", "DetailsProCust", new { id = item.id }) |
                @Html.ActionLink("Delete", "DeleteProjectCust", new { id = item.id })

                @using (Html.BeginForm("AssignMD", "Project", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()

                    @Html.DropDownListFor(m => m.projectAs.name_dm, new SelectList(Model.mds, "Username", "Username"), "Choose MD", new { @Name = "name_dm",id="mdsel", @class = "form-control", @style = "width:150px;height:33px;display:inline-block;font-size:12px" })
                    <input type="text" name="proId" value="@item.id" hidden />
                    <input type="text" name="usrname" value="@HttpContext.Current.User.Identity.Name" hidden />
                    <input type="submit" name="submit" value="add" style="width:50px;height:30px;border:none;border-radius:5px;cursor:pointer" />

                }
                <br />
                @*<p style="font-size:10px;margin-bottom:0px">marketing directors you've been assigned</p>*@
                <div>
                    <button class="collapsible" style="font-size:10px;margin-bottom:0px;background:none;border:none">marketing directors you've been assigned /<span style="font-size:7px">(click to close/open)</span></button>
                    <div class="content">
                        <table>

                            @foreach (var itemAs in Model.projectAsinss)
                            {
                                if (itemAs.proId == item.id)
                                {
                                    <tr style="font-size:small;">

                                        <td>

                                            @Html.DisplayFor(modelItem => itemAs.name_dm)
                                        </td>

                                        <td>
                                            <form action="/Project/DeleteMDAssign" method="post">
                                                <input type="text" name="id" value="@itemAs.id" hidden/>
                                                <i class='fas fa-user-alt-slash' style='font-size:12px;color:firebrick'></i>
                                                <input type="submit" style="color:firebrick;font-size:12px;background:none;border:none;margin:-10px;cursor:pointer" value="delete" />
                                            </form>
                                            @*<a href="/Project/DeleteMDAssign" style="color:firebrick"><i class='fas fa-user-alt-slash' style='font-size:12px'></i>delete</a>*@
                                        </td>
                                    </tr>
                                }
                            }
                        </table>
                    </div>
                </div>
            </td>
        </tr>

    }


</table>
<script>
    $(document).ready(function () {
        $("#mdsel option:first-child").attr("disabled", "true");
    });

</script>

<script>
    var coll = document.getElementsByClassName("collapsible");
    var i;

    for (i = 0; i < coll.length; i++) {
        coll[i].addEventListener("click", function () {
            
            this.classList.toggle("active");
            var content = this.nextElementSibling;
            if (content.style.display === "block") {
                content.style.display = "none";
            } else {
                content.style.display = "block";
            }
        });
    }
</script>

PMS/PMS/Views/Project/List_dm.cshtml
@model PMS.Models.ProjectAssignment

@{
    ViewBag.Title = "List_dm";
    Layout = "~/Views/Shared/_Customer_Trainee.cshtml";
}


<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
<h2>List_dm</h2>
<button id="hide">Hide</button>
<button id="show">Show</button>
<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(x => x.project.cust_name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.project.name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.project.descrption)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.project.stat)
        </th>

        <th></th>
    </tr>

    @foreach (var item in Model.projects)
    {
        <tr>
            
            <td>
                @Html.DisplayFor(modelItem => item.name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.descrption)
            </td>
            
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.id }) |
                @Html.ActionLink("Details", "Details", new { id = item.id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.id })

                @using (Html.BeginForm("AssignMD", "Project", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()

                    @Html.DropDownListFor(m => m.projectAs.name_dm, new SelectList(Model.mds, "Username", "Username"), "Choose MD", new { @Name = "name_dm", @class = "form-control", @style = "width:150px;height:33px;display:inline-block;font-size:14px" })
                    <input type="text" name="proId" value="@item.id" hidden />
                    <input type="text" name="usrname" value="@HttpContext.Current.User.Identity.Name" hidden />
                    <input type="submit" value="add" style="width:50px;height:30px;border:none;border-radius:5px;" />

                }
                <br />
                <p style="font-size:10px;margin-bottom:0px">marketing directors you've been assigned</p>
                <table>
                    @foreach (var itemAs in Model.projectAsinss)
                    {
                        if (itemAs.proId == item.id)
                        {
                            <tr style="font-size:small">

                                <td >
                                    @Html.DisplayFor(modelItem => itemAs.name_dm)
                                </td>

                                <td>
                                    <a href="#"><i class='fas fa-user-alt-slash' style='font-size:12px'></i>delete</a>
                                </td>
                            </tr>
                        }
                    }
                </table>

            </td>
        </tr>
 
    }

</table>

PMS/PMS/Views/Project/TestNotiDeleteProject.cshtml
@model PMS.Models.project

@{
    ViewBag.Title = "TestNotiDeleteProject";
    Layout = "~/Views/Shared/_admin_MD_TL.cshtml";
}

<h2>TestNotiDeleteProject</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>project</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.cust_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cust_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.descrption)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.descrption)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.stat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.stat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.user.Role)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.user.Role)
        </dd>

    </dl>

    @using (Html.BeginForm("TestNotiDeleteProject", "Project",FormMethod.Post)) {
        @Html.AntiForgeryToken()
       
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "TestNoti")
        </div>
    }
</div>